### PR TITLE
Support Spelunky 1.47 and Project Cleanup

### PR DESCRIPTION
**Pull request by gmjosack**
Apologies in advance in the project cleanup is unwelcome. If so feel free to take the offsets only.

* Removed all user and generated files from repo to clean up the checked in files
* Added Visual Studio specific gitignore to avoid user/gen files from getting checked in 
* Updated memory offsets to support Spelunky 1.47
* Updates Windows SDK version to 10
* Updates Platform Toolset to v142 (VS2019)
* Add DX SDK via NuGet so it's pulled automatically
* Remove Debug and x64 build targets
* moved config.txt to repo root and updated rules to copy into build output directory

**Note:** I didn't bump the version because I'm not sure if you want to bump the version for the GOG release as well. I also didn't update the readme yet because I figure that'd be done after a new release was pushed.

### CODE REVIEW

**Comment by gmjosack** [comment]
I understand this is probably low priority. Would be good to get an indication of whether you have plans to merge this or not. If not I'm happy to maintain a fork under the @spelunky-fyi org where we maintain lots of tools for all 3 spelunky games.

**Comment by ThomasTerp** [comment]
Thanks for the pull request and updating it for 1.47! The project cleanup is welcome, I didn't really know which files the repo should have when I made it. I will merge the pull request after I reviewed it.

**Comment by gmjosack** [comment]
I have another branch ready as well that merges the dll for steam in gog into a single dll to deduplicate the code but it's based off of this branch so I'll wait until this is merged before opening that.

**Comment by ThomasTerp** [comment]
Sounds good, I will create a new release once that pull request is merged too.

**Pull request merged**
